spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}?${DB_SSL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}

  jpa:
    show-sql: false
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
    hibernate:
      ddl-auto: none

  jackson:
    serialization:
      INDENT_OUTPUT: true

  liquibase:
    change-log: classpath:changelog/changelog-master.xml


#Google Recaptcha
recaptcha:
  url: ${RECAPTCHA_URL}
  key:
    secret: ${RECAPTCHA_KEY_SECRET}
    public: ${RECAPTCHA_KEY_PUBLIC}

#SSl
server:
  port: ${PORT_SSL}
  ssl:
    key-store-type: PKCS12
    key-store: ${PATH_TO_P12}
    key-store-password: ${KEYSTORE_PASSWORD_SSL}
    key-alias: ${KEY_ALIAS_SSL}
    enabled: true
    protocol: TLS

protection:
  timeout:
    numberofattempts: ${TIMEOUT_NUMBER_OF_ATTEMPTS}
    minutes: ${LOOKTIME_MINUTES}

card.service.cipher:
  keyStoragePassword: ${KEY_STORAGE_PASSWORD}
  cardEncryptPassword: ${CARD_ENCRYPT_PASSWORD}
  aliasCardKey: ${ALIAS_CARD_KEY}
  pathKeyStorage: ${PATH_KEY_STORAGE}
  typeKey: ${TYPE_KEY}
